<a href="https://colab.research.google.com/github/DimasWerito/Math_02/blob/main/Math_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
A = np.array(
    [[1,2],
     [3,4]]
)
print(round(np.linalg.det(A)))

-2


In [2]:
import numpy as np
A = (
    [[4,-5,7],
     [1,-4,9],
     [-4,0,5]]
)
print(round(np.linalg.det(A)))

13


In [3]:
"""
Властивість 1:
Визначник не змінюється під час транспонування матриці.
"""


import numpy as np
A = np.array(
    [[4,-5,7],
     [1,-4,9],
     [-4,0,5]]
)
At = np.transpose(A)
print("Початкова матриця А:")
print(A)
print(f"Визначник базової матриці А:{int(np.linalg.det(A))}")
print(At)
print(f"Визначник транспонованої матриці At:{int(np.linalg.det(At))}")

Початкова матриця А:
[[ 4 -5  7]
 [ 1 -4  9]
 [-4  0  5]]
Визначник базової матриці А:12
[[ 4  1 -4]
 [-5 -4  0]
 [ 7  9  5]]
Визначник транспонованої матриці At:12


In [4]:
"""
Властивість 2:
Якщо матриця містить рядок, що складається з нулів, її визначник дорівнює нулю.
"""


import numpy as np
A = (
    [[2,7,1,2],
     [6,1,3,-1],
     [0,0,0,0],
     [2,9,5,-1]]
)
print(f"Визначник матриці А:{int(np.linalg.det(A))}")


Визначник матриці А:0


In [9]:
"""
Властивість 3:
Якщо в матриці поміняти місцями якісь два рядки, то її визначник змінить знак на протилежний.
"""


import numpy as np
A = np.array(
    [[1,0,-1],
     [11,4,7],
     [-6,0,0]]
)
B = np.array(
    [[11,4,7],
     [1,0,-1],
     [-6,0,0]]
)
print(f"Визначник матриці A:{int(np.linalg.det(A))}")
print(f"Визначник матриці B:{int(np.linalg.det(B))}")

Визначник матриці A:-24
Визначник матриці B:24


In [10]:
"""
Властивість 4:
Якщо матриця має два однакові рядки, то її визначник дорівнює 0
"""


import numpy as np
A = np.array(
    [[2,7,1,2],
     [6,1,3,-1],
     [2,7,1,2],
     [2,9,5,-1]]
)
print(f"Визначник матриці А:{int(np.linalg.det(A))}")

Визначник матриці А:0


In [11]:
"""
Властивість 5:

При множенні рядка матриці на число її визначник множиться на це число.
"""


import numpy as np
A = np.array(
    [[2,4,-12],
     [10,3,0],
     [1,-1,1]]
)
B = np.array(
    [[1,2,-6],
     [10,3,0],
     [1,-1,1]]
)
print(f"Визначник матриці А:{int(np.linalg.det(A))}")
print(f"Визначник матриці B:{int(np.linalg.det(B))}")

Визначник матриці А:122
Визначник матриці B:61


In [12]:
"""
Властивість 6

"""


import numpy as np
A = np.array(
    [[6,4,12],
     [10,3,0],
     [1,-1,1]]
)
B = np.array(
    [[2,3,9],
     [10,3,0],
     [1,-1,1]]
)
C = np.array(
    [[4,1,3],
     [10,3,0],
     [1,-1,1]]
)
print(f"Визначник матриці A:{round(np.linalg.det(A))}")
print(f"Визначник матриці B:{round(np.linalg.det(B))}")
print(f"Визначник матриці C:{round(np.linalg.det(C))}")

Визначник матриці A:-178
Визначник матриці B:-141
Визначник матриці C:-37


In [13]:
"""
Властивість 7

Якщо один із рядків матриці є лінійною комбінацією інших рядків цієї матриці, то її визначник дорівнює нулю.
"""


import numpy as np
A = np.array(
    [[2,7,-1],
     [0,1,3],
     [2,9,5]]
)
print(f"Визначник матриці A:{round(np.linalg.det(A))}")

Визначник матриці A:0


In [14]:
"""
Властивість 8

Якщо до елементів рядка (стовпця) визначника додати відповідні елементи іншого рядка (стовпця), помножені на будь-яке число, то визначник не зміниться.
"""


import numpy as np
A = np.array(
    [[3,8,0],
     [1,1,1],
     [2,9,5]]
)
B = np.array(
    [[2,7,-1],
     [1,1,1],
     [2,9,5]]
)
print(f"Визначник матриці A:{round(np.linalg.det(A))}")
print(f"Визначник матриці B:{round(np.linalg.det(B))}")

Визначник матриці A:-36
Визначник матриці B:-36
