<a href="https://colab.research.google.com/github/DimasWerito/Math_02/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%BD%D1%96_%D0%B2%D0%BF%D1%80%D0%B0%D0%B2%D0%B8_%D0%BD%D0%B0_%D0%B7%D0%B0%D0%BD%D1%8F%D1%82%D1%82%D1%8F_2_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Розв'язання рівнянь із використанням матриць

>[Розв'язання рівнянь із використанням матриць](#scrollTo=YUF47db79LlZ)

>>[Матричний запис рівняння](#scrollTo=fA1qh_MhjHL5)

>>[Обрахунок визначника](#scrollTo=TLLV9reOjsIK)

>>[Обернена матриця](#scrollTo=NnaVHRnLjvUJ)

>>[Розв'язання СЛАР](#scrollTo=ajIp3eGqjwDG)

>>[Матричне рівняння](#scrollTo=h_g4cqYrmZrZ)

>>[Метод Крамера](#scrollTo=j72LZYoVmdsB)

>>[Метод Гаусса](#scrollTo=mZNwWtEv-rtw)

>[Обчислення визначника з трикутної матриці](#scrollTo=VId4AHzAN-Az)



## Матричний запис рівняння
Зробіть матричний запис наступних рівнянь:  
$
\begin{cases}
5x + z = 65 \\
-x - 4y + 1z = 25 \\
4x + 3y + 6z = 30 \end{cases}
$

$
\begin{cases}
5x = 65 \\
4y + z = 25 \\
4x + y  = 30 \end{cases}
$

$
\begin{cases}
5x + k = 65 \\
4y + z + k = 25 \\
k = 25 \\
4x + y  = 30 \end{cases}
$

**Додаткове завдання:**
1. Напишіть програму, яка генерує приклади рівнянь для запису їх у вигляді матриць.
2. Яка умова має виконуватись, щоб система лініших алгебраїчних рівнянь мала розв'язок?






Спробуємо розробити універсальні функції для перетворення записанних строкових рівнянь у відповідні матриці

In [ ]:
import numpy as np

Суттєвим елементом таких функцій буде функція split()

In [ ]:
eqs = ['5x + z = 65', '-1x - 4y + 1z = 25', '4x + 3y + 6z = 30']
variables = ['x', 'y', 'z']
left = eqs[0].split('=')[0]
right = eqs[0].split('=')[1]

print(eqs[1].split('y'))


['-1x - 4', ' + 1z = 25']


In [ ]:
def replace_space(lst, old_char, new_char):
    new_list = [s.replace(old_char, new_char) for s in lst]
    return new_list

In [1]:
def create_linear_system(equations, variables):

    equations = replace_space(equations, '- ', '-')
    num_equations = len(equations)
    num_variables = len(variables)

    coeff_matrix = np.zeros((num_equations, num_variables))
    right_coeff = np.zeros(num_equations)

    for i, equation in enumerate(equations):
        terms = equation.split()
        for term in terms:
            for j, variable in enumerate(variables):
                if variable in term:
                    coeff = term.split(variable)[0]
                    if coeff:
                        coeff_matrix[i, j] = float(coeff)
                    else:
                        coeff_matrix[i, j] = 1
        right_coeff[i] = float(equation.split('=')[1])

    return coeff_matrix, right_coeff



In [ ]:
equations = ['5x + z = 65', '-1x - 4y + z = 25', '4x + 3y + 6z = 30']
variables = ['x', 'y', 'z']

create_linear_system(equations, variables)

(array([[ 5.,  0.,  1.],
        [-1., -4.,  1.],
        [ 4.,  3.,  6.]]),
 array([65., 25., 30.]))

## Обчислення визначника
Обрахуйте наступні визначники:  
1. $\begin{vmatrix}
−2& −3 &1 \\
0 &1& 4\\
2& −2& 0\end{vmatrix}$  
2. $\begin{vmatrix}
3&2 &1& 3\\
1& 3& 0& 4\\
0& −2& 2& 1\\
2& 4& 0& 5
\end{vmatrix} $.

3.
$\begin{vmatrix}
−2& 3& 2 &−1\\
3& 0 &1 &2\\
1& 2& 0 &1\\
5& 0 &7 &−3
\end{vmatrix} $.



In [ ]:
A = np.array([[-2, -3, 1],
                        [0, 1, 4],
                        [2, -2, 0]])
np.linalg.det(A)

-41.999999999999986

## Обчислення визначника через алгебраїчні доповнення

In [ ]:

def submatrix(matrix, row, col):
    return np.delete(np.delete(matrix, row, axis=0), col, axis=1)


def minor(matrix, i, j):
    # Обчислюємо мінор для елемента у рядку i та стовпці j
    return determinant(submatrix(matrix, i, j))

def determinant(matrix):
    # Базовий випадок - для матриці 1x1
    if len(matrix) == 1:
        return matrix[0][0]

    det = 0
    for j in range(len(matrix[0])):
        # Обчислюємо алгебраїчний доповнення для кожного елемента першого рядка
        sign = (-1) ** j
        cofactor = matrix[0][j]
        det += sign * cofactor * minor(matrix, 0, j)
    return det



In [ ]:
determinant(A)

-42

## Обернена матриця
Знайдіть обернені матриці. Перевірте себе (добуток матриці та її оберненої матриці дорівнює одиничній матриці)

$A=\begin{pmatrix}
−1 &0 &3\\
6& 3& −1\\
3 &−2 &−3
\end{pmatrix}$


$B=\begin{pmatrix}
−1& −2& −2\\
3 &3 &1\\
2 &0& −3
\end{pmatrix}$

$C=\begin{pmatrix}
3 &0 &−1\\
2& 5& 2\\
−1& 2 &7
\end{pmatrix}$

**Додаткове завдання:**
1. Напишіть програму обчислення оберненої матриці до заданої.


In [ ]:
def inverse(matrix):
    det = determinant(matrix)
    if det == 0:
        raise ValueError("Матриця є сингулярною (не має оберненої матриці).")

    n = len(matrix)
    # Coюзна (доповнена) матриця
    adjugate = [[(-1)**(i+j) * minor(matrix, i, j) for j in range(n)] for i in range(n)]
    adjugate_transpose = [[adjugate[j][i] for j in range(n)] for i in range(n)]

    inverse_matrix = [[adjugate_transpose[i][j] / det for j in range(n)] for i in range(n)]
    return inverse_matrix



In [ ]:
inverse(A)

[[-0.19047619047619047, 0.047619047619047616, 0.30952380952380953],
 [-0.19047619047619047, 0.047619047619047616, -0.19047619047619047],
 [0.047619047619047616, 0.23809523809523808, 0.047619047619047616]]

In [ ]:
np.linalg.inv(A)

array([[-0.19047619,  0.04761905,  0.30952381],
       [-0.19047619,  0.04761905, -0.19047619],
       [ 0.04761905,  0.23809524,  0.04761905]])

## Розв'язання СЛАР

$
\begin{cases}
3 x+2 y+ z=5 \\
2 x−y+z=6 \\
x+5 y=−3.\end{cases}
$

$
\begin{cases}
2 x_{{1}}−3 x_{{2}}+4 x_{{3}}=5\\
3 x_{{1}}+ x_{{2}}+ x_{{3}}=8\\
4 x _{{1}}−2 x_{{2}}−3 x_{{3}}=3.\end{cases}$
  

* Чи є якась відмінність при вирішенні СЛАР при записі невідомих через $x,y,z$ та через $x_{{1}},x_{{2}},x_{{3}}$?



$
\begin{cases}
3 x_{{1}}−2 x_{{2}}+x_{{3}}=4\\
x_{{1}}+x_{{3}}=2\\
x_{{1}}-2 x_{{2}}−x_{{3}}=4.\end{cases}
$

**Додаткове завдання:**
1. Напишіть програму вирішення систем алгебраїчних рівнянь матричним методом.
2. Напишіть програму вирішення систем алгебраїчних рівнянь методом Гауса.

##Матричне рівняння

In [ ]:
equations = ['3x + 2y + z = 5', '2x - 1y + z = 6', 'x + 5y = -3']
vars = ['x', 'y', 'z']
A, b = create_linear_system(equations, vars)

Розв'язок матричного рівняння $ AX = b $

$ A^{-1} AX = A^{-1}b$,

отже

$ X = A^{-1}b $

In [ ]:
A_inv = inverse(A)
A_inv

[[2.5, -2.5, -1.5], [-0.5, 0.5, 0.5], [-5.5, 6.5, 3.5]]

In [ ]:
np.linalg.inv(A)

array([[ 2.5, -2.5, -1.5],
       [-0.5,  0.5,  0.5],
       [-5.5,  6.5,  3.5]])

In [ ]:
X = np.array(A_inv).dot(b)
X

array([ 2., -1.,  1.])

In [ ]:
print(np.linalg.solve(A, b))

[ 2. -1.  1.]


## Метод Крамера

$
\begin{cases}
3 x+2 y+ z=5 \\
2 x−y+z=6 \\
x+5 y=−3.\end{cases}
$


![picture](https://drive.google.com/uc?id=1Fp57cxg3wdzVMxwjHm4VFq4MHs8O0hwf)


In [ ]:


def solve_using_kramer(A, b):

    mA, mb = np.copy(A), np.copy(b)
    n = len(mb)
    det_A = np.linalg.det(mA)

    if det_A == 0:
        return None  # Система не має розв'язку

    x = np.zeros(n)
    for i in range(n):
        Ai = mA.copy()
        Ai[:, i] = mb
        x[i] = np.linalg.det(Ai) / det_A

    return x


In [ ]:
solve_using_kramer(A, b)

array([ 2., -1.,  1.])

## Метод Гаусса


![picture](https://drive.google.com/uc?id=1SxnmjnSRWiiXLJEr1WYHgKlI-AUmnSCW)



In [ ]:
def gaussian_elimination(A, b):
    print(np.array(A))
    print(np.array(b))
    mA, mb = np.copy(A), np.copy(b)


    n = len(mb)
    for i in range(n):
        # Пошук головного (опорного) елемента у стопцях
        print('---- iter ----', i)
        pivot_row = i
        for j in range(i+1, n):
            if abs(mA[j, i]) > abs(mA[pivot_row, i]):
                pivot_row = j

        # Перестановка строк, щоб головний елемент опинився на головній діагоналі
        mA[[i, pivot_row]] = mA[[pivot_row, i]]
        mb[[i, pivot_row]] = mb[[pivot_row, i]]
        print('pivot_row', pivot_row)
        print(np.array(mA))
        print(np.array(mb))

        # Застосування еквівалентних перетворень
        for j in range(i+1, n):
            factor = mA[j, i] / mA[i, i]
            mb[j] -= factor * mb[i]
            mA[j, i:] -= factor * mA[i, i:]

    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (mb[i] - np.dot(mA[i, i+1:], x[i+1:])) / mA[i, i]
    return x, mA



In [ ]:
x, trianglA = gaussian_elimination(A, b)

[[ 3.  2.  1.]
 [ 2. -1.  1.]
 [ 1.  5.  0.]]
[ 5.  6. -3.]
---- iter ---- 0
pivot_row 0
[[ 3.  2.  1.]
 [ 2. -1.  1.]
 [ 1.  5.  0.]]
[ 5.  6. -3.]
---- iter ---- 1
pivot_row 2
[[ 3.          2.          1.        ]
 [ 0.          4.33333333 -0.33333333]
 [ 0.         -2.33333333  0.33333333]]
[ 5.         -4.66666667  2.66666667]
---- iter ---- 2
pivot_row 2
[[ 3.          2.          1.        ]
 [ 0.          4.33333333 -0.33333333]
 [ 0.          0.          0.15384615]]
[ 5.         -4.66666667  0.15384615]


#Обчислення визначника з трикутної матриці

Трикутну матрицю, що є результатом роботи алгоритма Гаусса, можна використовувати для обчислення визначника.

Адже визначник трикутної матриці дорівнює добутку діагональних елементів.

Важливо! Якщо в ході роботи алгоритма Гаусса змінювався порядок строк, ще буде впливати на знак визначника. В цьому випадку добутку діагональних елементів потрібно помножити на (-1) у степені кількості перестановок строк.  

In [ ]:
trianglA

array([[ 3.        ,  2.        ,  1.        ],
       [ 0.        ,  4.33333333, -0.33333333],
       [ 0.        ,  0.        ,  0.15384615]])

In [ ]:
det = np.prod(np.diagonal(trianglA))
det

2.000000000000001

Оскільки в попередньому прикладі роботи метода Гаусса була одна перестановка строк, отримане значення визначника потрібно помножити на $(-1)^{1}$. Тобто, відповідь: -2